---
galaxy_info:
  author: Lorin Hochstein
  description: Install Mezzanine
  license: BSD
  min_ansible_version: 1.7
  platforms:
    - name: Ubuntu
      versions:
      - trusty
  categories:
    - web
dependencies: []
